# Generated by Django 5.0.6 on 2024-05-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cus_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.CharField(max_length=55),
        ),
    ]
