# Generated by Django 5.0.6 on 2024-05-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_eventlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventlist',
        ),
    ]
