# Generated by Django 5.0.6 on 2024-06-30 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew_memper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrewMember',
        ),
    ]
