# Generated by Django 5.0.6 on 2024-06-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0003_alter_booking_cus_name_alter_booking_cus_ph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='descr',
            field=models.CharField(max_length=100),
        ),
    ]
